name: "Question"
description: "Ask a question about the Signeo project."
title: "[QUESTION] Your question here"
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: "Your Question"
      placeholder: "Ask your question here."
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Any additional information or context for your question."
      placeholder: "Add any supporting information or links."
